### ISSUE TITLE
how to withdraw sats in the address of lightning-gifts

### ISSUE THREAD

**Issue by salamsoliman** [baebb/react-lightning-gifts#6]
if someone send some sats to the generated address  by lightning-gifts,how to how to withdraw them?

**Comment by baebb** [comment]
After you pay the invoice the app will generate a unique lightning.gifts URL for your new gift eg. `https://lightning.gifts/redeem/004ba6c0c681b7d611dfcc775d04935afd1ae2e2c206b302`
