### ISSUE TITLE
I successfully charged 103 sats into generated address, but not get redeemable qr .

### ISSUE THREAD

**Issue by salamsoliman** [baebb/react-lightning-gifts#8]
I charged 103 satoshi  into this following address on https://lightning.gifts/
LNBC1030N1PW78ZXSPP5EF4WZPW4TWYH0V9CUPXQNFRA3M2D3GDTU50TDRMWP35F3Y9VE5SQDPVF35KW6R5DE5KUEEQVA5KVAPQVEHHYGP3XQEJQUMPW3ESCQZPG2STFGVQQYY54P65AVKX5ZNWH9QT0Q6REPC5JNHZ5MAN7EPV3TX49U87C9PFC7VH27CFST7WJD3X0RAEVJPP0N26DMWPU9VMTH6TMZVGP0J2RRY 

but not , the webpage displayed redeemable qr code and review link automatically.

**Comment by baebb** [comment]
Here's your gift: https://lightning.gifts/redeem/90b80740554386ee41db41ef4b740757f256446476da0683

Sometimes it's might take up to 30 seconds to create

**Comment by salamsoliman** [comment]
Thanks,got it.
